name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-conditional-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
      - uses: akhileshns/heroku-deploy@v3.12.12
        if: github.ref == 'refs/heads/main'
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'plantumlive'
          heroku_email: 'kkweon@gmail.com'
